install.packages(c("slidify","ggplot2","devtools"))
library(ggplot2)
search()
install.packages("pastecs")
library(pastecs)

read.csv(file.choose(), stringsAsFactors = F)
burger<-read.csv(file.choose(), stringsAsFactors = F)
head(burger)
summary(burger)
summary(burger['Amount.Burger'])
summary(burger['Amount.Drink'])
stat.desc(burger['Amount.Burger'])
stat.desc(burger['Amount.Drink'])
